- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name : nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download catalogue aplication
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
    
  - name: Extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install depedencies
    ansible.builtin.command: npm install
    args:
        chdir: /app

  - name: Copy catalogue service
    ansibe.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true
      
  name: Copy mongodb repo
    ansibe.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install mongodb
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
